"""
Contains static champion data
"""

CHAMPIONS = {
    "Aatrox": {"Gold": 1, "Board Size": 1},
    "Anivia": {"Gold": 3, "Board Size": 1},
    "Ao Shin": {"Gold": 10, "Board Size": 2},
    "Ashe": {"Gold": 2, "Board Size": 1},
    "Aurelion Sol": {"Gold": 10, "Board Size": 2},
    "Bard": {"Gold": 5, "Board Size": 1},
    "Braum": {"Gold": 2, "Board Size": 1},
    "Corki": {"Gold": 4, "Board Size": 1},
    "Daeja": {"Gold": 8, "Board Size": 2},
    "Diana": {"Gold": 3, "Board Size": 1},
    "Elise": {"Gold": 3, "Board Size": 1},
    "Ezreal": {"Gold": 1, "Board Size": 1},
    "Gnar": {"Gold": 2, "Board Size": 1},
    "Hecarim": {"Gold": 4, "Board Size": 1},
    "Heimerdinger": {"Gold": 1, "Board Size": 1},
    "Idas": {"Gold": 8, "Board Size": 2},
    "Illaoi": {"Gold": 3, "Board Size": 1},
    "Jinx": {"Gold": 2, "Board Size": 1},
    "Karma": {"Gold": 1, "Board Size": 1},
    "Kayn": {"Gold": 2, "Board Size": 1},
    "Lee sin": {"Gold": 3, "Board Size": 1},
    "Leona": {"Gold": 1, "Board Size": 1},
    "Lillia": {"Gold": 2, "Board Size": 1},
    "Lulu": {"Gold": 3, "Board Size": 1},
    "Nami": {"Gold": 2, "Board Size": 1},
    "Neeko": {"Gold": 4, "Board Size": 1},
    "Nidalee": {"Gold": 1, "Board Size": 1},
    "Nunu": {"Gold": 3, "Board Size": 1},
    "Olaf": {"Gold": 3, "Board Size": 1},
    "Ornn": {"Gold": 4, "Board Size": 1},
    "Pyke": {"Gold": 5, "Board Size": 1},
    "Qiyana": {"Gold": 2, "Board Size": 1},
    "Ryze": {"Gold": 3, "Board Size": 1},
    "Sejuani": {"Gold": 1, "Board Size": 1},
    "Senna": {"Gold": 1, "Board Size": 1},
    "Sett": {"Gold": 1, "Board Size": 1},
    "Shen": {"Gold": 2, "Board Size": 1},
    "Shi Oh Yu": {"Gold": 8, "Board Size": 2},
    "Shyvana": {"Gold": 10, "Board Size": 2},
    "Skarner": {"Gold": 1, "Board Size": 1},
    "Sona": {"Gold": 4, "Board Size": 1},
    "Soraka": {"Gold": 5, "Board Size": 1},
    "Swain": {"Gold": 3, "Board Size": 1},
    "Syfen": {"Gold": 8, "Board Size": 2},
    "Sylas": {"Gold": 3, "Board Size": 1},
    "Tahm Kench": {"Gold": 1, "Board Size": 1},
    "Talon": {"Gold": 4, "Board Size": 1},
    "Taric": {"Gold": 1, "Board Size": 1},
    "Thresh": {"Gold": 2, "Board Size": 1},
    "Tristana": {"Gold": 2, "Board Size": 1},
    "Twitch": {"Gold": 2, "Board Size": 1},
    "Varus": {"Gold": 3, "Board Size": 1},
    "Vladmir": {"Gold": 1, "Board Size": 1},
    "Volibear": {"Gold": 3, "Board Size": 1},
    "Xayah": {"Gold": 4, "Board Size": 1},
    "Yasuo": {"Gold": 5, "Board Size": 1},
    "Yone": {"Gold": 2, "Board Size": 1},
    "Zoe": {"Gold": 5, "Board Size": 1}}
